### ISSUE TITLE
[Termék/felhasználó fókusz] BDD tesztek készítése

### ISSUE THREAD

**Issue by domonkosadam** [BME-MIT-IET/iet-hf-2023-service-unavailable#3]
# BDD tesztek készítése
Viselkedésvezérelt fejlesztési tesztek készítése
Tesztelő eszköz: [Cucumber](https://cucumber.io/)
@domonkosadam: Főoldal tesztelése: Útvonalak létrehozása, módosítása, rendezése, törlése
@Tschonti: Teljesítések oldal tesztelése - Teljesítések létrehozása, módosítása, törlése

**Comment by Tschonti** [comment]
Közös megegyzés után úgy döntöttünk, hogy ezt a feladatot mégsem végezzük el.
